### ISSUE TITLE
Partition shown as full even with a single small file

### ISSUE THREAD

**Issue by Kilklang26** [danielgjackson/virtualdisk#1]
Hi,
I discovered your project and try to use for emulating a mass storage USB device, i combined it with USB stack on a microcontroller. It works well for reporting device size, file size, it shows the file on the explorer (Windows), I can read that file.
However, no matter how many clusters the partition has, Windows says there are 0 bytes free. So I cannot play with file writes.

I created an image of the partition to look at it with an hex editor, and it seems that the FAT table is full of incrementing numbers (coded on two bytes). I'm not an expert on this, but maybe that's why Windows thinks there is more data allocated?
I this is a bug or maybe I don't use your library correctly? Sorry if this is a dumb question. Any help appreciated.
![free space](https://github.com/danielgjackson/virtualdisk/assets/91727188/799eb196-233a-4d57-8d54-430a3c218326)

**Comment by danielgjackson** [comment]
Hi @Kilklang26!

Sorry, it looks like I forgot to make it clear that it's a **read-only** drive.  I'm afraid supporting writing would mean that you have to allow arbitrary writing by an operating system to anywhere on the disk (e.g. even a full format and replacing all of the files), and you would actually have to have the full drive space available.  If you did, you may as well use a full disk implementation.  

There is an exception which would be to just pretend to allow disk writes and deal with specifically-crafted sector writes (some devices are reflashed in this way).

If you need writes in a more controlled way, you could consider alternatives to mass storage class, such as USB Picture Transfer Protocol / Media Transfer Protocol -- where (I believe) you can accept files as objects (rather than sector writes to a whole filesystem).

I hope this helps! Cheers.

**Comment by Kilklang26** [comment]
Thank you for your answer! I'll look into MTP next
